# Generated by Django 4.0 on 2022-02-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('head0', models.CharField(max_length=90000000)),
                ('chead0', models.CharField(max_length=98669876787)),
                ('head1', models.CharField(max_length=7462646)),
                ('chead1', models.CharField(max_length=9374854877846)),
                ('head2', models.CharField(max_length=5767576865)),
                ('chead2', models.CharField(max_length=89347427374)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default=' ', upload_to='blog/images')),
            ],
        ),
    ]
