# Generated by Django 4.0 on 2022-01-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_cat', models.CharField(max_length=100)),
                ('product_subcat', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_desc', models.CharField(max_length=300)),
                ('product_date', models.DateField()),
                ('product_image', models.ImageField(default=' ', upload_to='shop/images')),
            ],
        ),
    ]
