# Generated by Django 4.0 on 2022-01-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.CharField(max_length=50)),
                ('contact_phone', models.IntegerField(max_length=10)),
                ('contact_desc', models.CharField(max_length=10000)),
            ],
        ),
    ]
