# Generated by Django 4.0 on 2022-02-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_contact_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('itemJson', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=6)),
            ],
        ),
    ]
