# Generated by Django 4.0 on 2022-02-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tel',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
