# Generated by Django 4.0.2 on 2022-02-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('about_id', models.AutoField(primary_key=True, serialize=False)),
                ('Head', models.CharField(max_length=10000)),
                ('SHead', models.CharField(max_length=1000000000)),
                ('Image', models.ImageField(default=' ', upload_to='shop/images')),
            ],
        ),
    ]
