# Generated by Django 4.0.2 on 2022-02-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='HeadMute',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
